### ISSUE TITLE
broken in build 98

### ISSUE THREAD

**Issue by lotus8962** [lassombra/FiremanAssist#25]
i close the game for 5 minutes and an update breaks all my favorite mods. fireman assistant isnt an option on the radio anymore. could possibly be an issue with the comms radio api, but idk.

**Comment by lassombra** [comment]
Update comms radio api - but there is also an issue with this build I should have a new build out in about 20 minutes.

**Comment by lassombra** [comment]
Unity mod manager should be offering you and update - if not you can download it here, 1.0.2 fixes this.
